homepage:
    path:     /
    defaults: { _controller: DataBaseBundle:Main:index }

new:
    path:     /ajax_request
    defaults: { _controller: DataBaseBundle:Main:new }


register_page:
    path:     /register
    defaults: { _controller: DataBaseBundle:Registration:register }

login:
    path:     /login
    defaults: { _controller: DataBaseBundle:Security:login }

create:
    path:     /create
    defaults: { _controller: DataBaseBundle:Faculty:choice }

show:
    path:     /show
    defaults: { _controller: DataBaseBundle:Main:show }

