DataBaseBundle\Entity\Curriculum:
    type: entity
    table: curriculum
    indexes:
        Profile_Curriculum:
            columns:
                - NameOfProfile
    uniqueConstraints:
        NumberOfTheCurriculum_UNIQUE:
            columns:
                - NumberOfTheCurriculum
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateofcreation:
            type: date
            nullable: true
            column: DateOfCreation
        numberofthecurriculum:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: NumberOfTheCurriculum
        assignedacademicdegree:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: AssignedAcademicDegree
        normativeeducationperiod:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: NormativeEducationPeriod
        formofstudy:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: FormOfStudy
        fgos:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FGOS
    manyToOne:
        nameofprofile:
            targetEntity: Profile
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                NameOfProfile:
                    referencedColumnName: NameOfProfile
            orphanRemoval: false
    lifecycleCallbacks: {  }
