DataBaseBundle\Entity\Department:
    type: entity
    table: department
    indexes:
        Faculty_Department:
            columns:
                - CodeOfFaculty
    uniqueConstraints:
        CodeOfDepartment_UNIQUE:
            columns:
                - CodeOfDepartment
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameofdepartment:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NameOfDepartment
        codeofdepartment:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            column: CodeOfDepartment
    manyToOne:
        codeoffaculty:
            targetEntity: Faculty
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CodeOfFaculty:
                    referencedColumnName: CodeOfFaculty
            orphanRemoval: false
    lifecycleCallbacks: {  }
