DataBaseBundle\Entity\Faculty:
    type: entity
    table: faculty
    uniqueConstraints:
        CodeOfFaculty_UNIQUE:
            columns:
                - CodeOfFaculty
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameoffaculty:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NameOfFaculty
        codeoffaculty:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: CodeOfFaculty
    lifecycleCallbacks: {  }
