DataBaseBundle\Entity\Specialty:
    type: entity
    table: specialty
    indexes:
        Faculty_Specialty:
            columns:
                - CodeOfFaculty
    uniqueConstraints:
        CodeOfSpecialty_UNIQUE:
            columns:
                - CodeOfSpecialty
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codeofspecialty:
            type: string
            nullable: false
            length: 6
            options:
                fixed: false
            column: CodeOfSpecialty
        nameofspecialty:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NameOfSpecialty
    manyToOne:
        codeoffaculty:
            targetEntity: Faculty
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CodeOfFaculty:
                    referencedColumnName: CodeOfFaculty
            orphanRemoval: false
    lifecycleCallbacks: {  }
