DataBaseBundle\Entity\Subject:
    type: entity
    table: subject
    indexes:
        Department_Subject:
            columns:
                - CodeOfDepartment
    uniqueConstraints:
        CodeOfSubject_UNIQUE:
            columns:
                - CodeOfSubject
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameofsubject:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NameOfSubject
        codeofsubject:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: CodeOfSubject
    manyToOne:
        codeofdepartment:
            targetEntity: Department
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CodeOfDepartment:
                    referencedColumnName: CodeOfDepartment
            orphanRemoval: false
    lifecycleCallbacks: {  }
