DataBaseBundle\Entity\Typeofclass:
    type: entity
    table: typeofclass
    uniqueConstraints:
        TypeOfClass_UNIQUE:
            columns:
                - TypeOfClass
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeofclass:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: TypeOfClass
        shortformofrecord:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: ShortFormOfRecord
    lifecycleCallbacks: {  }
