DataBaseBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
        username_UNIQUE:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
    lifecycleCallbacks: {  }
